apiVersion: apps/v1
kind: Deployment
metadata:
  name: shsxctf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shsxctf
  template:
    metadata:
      labels:
        app: shsxctf
    spec:
      containers:
        - name: react-app
          image: menisisaac/shsxctf-frontend:latest
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: trccred
