apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
   
  rules:
   
    - host: hello-world.info 
    
      http:
   
        paths:
   
          - path: /hi/.*
   
            pathType: Prefix
   
            backend:
   
              service:
   
                name: webapp-service
   
                port:
   
                  number: 8080
