apiVersion: v1
kind: Service
metadata:
  name: shsxctf-webapp
spec:
  type: NodePort
  selector:
    app: shsxctf-webapp
  ports:
  - port: 3050
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
view raw
