name: Admin Build

on:
  push:
    paths:
      - 'admin/**'
     
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps: 
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            menisisaac/shsxctf-admin:latest
            menisisaac/shsxctf-admin:${{ github.sha }}
          context: "{{defaultContext}}:admin"
          
  deploy:
    name: Deploy
    runs-on: self-hosted
    
    steps:
      - name: Remove existing containers
        run: docker rm $(docker stop $(docker ps -a -q --filter ancestor=menisisaac/shsxctf-admin:latest --format="{{.ID}}"))
        
      - name: Pull latest images
        run: docker pull menisisaac/shsxctf-admin:latest
        
      - name: Run images
        run: docker run -d -p 8082:8082 menisisaac/shsxctf-admin:latest
        
  
    
